### ISSUE TITLE
Buttons to toggle through years are not working

### ISSUE THREAD

**Issue by Lemonne** [Lemonne/Globex#5]
When a button is pressed to toggle through years, the graph is not accurately updated. 
When the page is loaded: 
![image](https://cloud.githubusercontent.com/assets/9356998/11552506/41cb62d0-993a-11e5-8364-542c5a9ef828.png)

After the button to the right is pressed: 
![image](https://cloud.githubusercontent.com/assets/9356998/11552509/53eed5b4-993a-11e5-9bdf-3615692a38f4.png)

**Comment by phillipj17** [comment]
This is now working perfectly!
